name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Backend to Heroku
        uses: behe/heroku-build@v1
        with:
          app-name: "qrdp-doc-uploader"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          path: "backend"
      - name: Deploy Doc-System to Heroku
        uses: behe/heroku-build@v1
        with:
          app-name: "qrdp-doc-system"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          path: "frontend/document-system"
